# Generated by Django 2.1.7 on 2019-07-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bname', models.CharField(blank=True, max_length=255, null=True)),
                ('book_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'books_easy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Books')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
