# Generated by Django 2.1.7 on 2019-07-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user_id',
            new_name='no_copies',
        ),
    ]
