# Generated by Django 2.1.7 on 2019-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190703_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_id',
        ),
    ]
