# Generated by Django 2.1.7 on 2019-07-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_books_remainder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='remainder',
        ),
    ]
